package DAS_ML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_StatusEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_StatusEnum() {
    super(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5ff4L, "StatusEnum", "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310068");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NORMAL_0 = new EnumerationDescriptor.MemberDescriptor("NORMAL", "NORMAL", 0x7c73d2235ccb5ff5L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310069");
  private final EnumerationDescriptor.MemberDescriptor myMember_ERROR_0 = new EnumerationDescriptor.MemberDescriptor("ERROR", "ERROR", 0x7c73d2235ccb5ff9L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310073");
  private final EnumerationDescriptor.MemberDescriptor myMember_READY_TO_START_0 = new EnumerationDescriptor.MemberDescriptor("READY_TO_START", "READY_TO_START", 0x7c73d2235ccb5ffaL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310074");
  private final EnumerationDescriptor.MemberDescriptor myMember_ACTIVATED_0 = new EnumerationDescriptor.MemberDescriptor("ACTIVATED", "ACTIVATED", 0x7c73d2235ccb5ffcL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310076");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEACTIVATED_0 = new EnumerationDescriptor.MemberDescriptor("DEACTIVATED", "DEACTIVATED", 0x7c73d2235ccb5ffdL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310077");
  private final EnumerationDescriptor.MemberDescriptor myMember_CALIBRATING_0 = new EnumerationDescriptor.MemberDescriptor("CALIBRATING", "CALIBRATING", 0x7c73d2235ccb5ffeL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310078");
  private final EnumerationDescriptor.MemberDescriptor myMember_NEED_CALIBRATION_0 = new EnumerationDescriptor.MemberDescriptor("NEED_CALIBRATION", "NEED_CALIBRATION", 0x7c73d2235ccb5fffL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310079");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5ff4L, 0x7c73d2235ccb5ff5L, 0x7c73d2235ccb5ff9L, 0x7c73d2235ccb5ffaL, 0x7c73d2235ccb5ffcL, 0x7c73d2235ccb5ffdL, 0x7c73d2235ccb5ffeL, 0x7c73d2235ccb5fffL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NORMAL_0, myMember_ERROR_0, myMember_READY_TO_START_0, myMember_ACTIVATED_0, myMember_DEACTIVATED_0, myMember_CALIBRATING_0, myMember_NEED_CALIBRATION_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NORMAL":
        return myMember_NORMAL_0;
      case "ERROR":
        return myMember_ERROR_0;
      case "READY_TO_START":
        return myMember_READY_TO_START_0;
      case "ACTIVATED":
        return myMember_ACTIVATED_0;
      case "DEACTIVATED":
        return myMember_DEACTIVATED_0;
      case "CALIBRATING":
        return myMember_CALIBRATING_0;
      case "NEED_CALIBRATION":
        return myMember_NEED_CALIBRATION_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
