package DAS_ML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RelationalOperatorEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RelationalOperatorEnum() {
    super(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5fd8L, "RelationalOperatorEnum", "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310040");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("EQUAL", "==", 0x7c73d2235ccb5fddL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310045");
  private final EnumerationDescriptor.MemberDescriptor myMember_NOT_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("NOT_EQUAL", "!=", 0x7c73d2235ccb5fe0L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310048");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_0 = new EnumerationDescriptor.MemberDescriptor("GREATER", ">", 0x7c73d2235ccb5fe2L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310050");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("GREATER_EQUAL", ">=", 0x7c73d2235ccb5fe4L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310052");
  private final EnumerationDescriptor.MemberDescriptor myMember_LESS_0 = new EnumerationDescriptor.MemberDescriptor("LESS", "<", 0x7c73d2235ccb5fe6L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310054");
  private final EnumerationDescriptor.MemberDescriptor myMember_LESS_EQUA_0 = new EnumerationDescriptor.MemberDescriptor("LESS_EQUA", "<=", 0x7c73d2235ccb5fe8L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/8967742332347310056");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5fd8L, 0x7c73d2235ccb5fddL, 0x7c73d2235ccb5fe0L, 0x7c73d2235ccb5fe2L, 0x7c73d2235ccb5fe4L, 0x7c73d2235ccb5fe6L, 0x7c73d2235ccb5fe8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_EQUAL_0, myMember_NOT_EQUAL_0, myMember_GREATER_0, myMember_GREATER_EQUAL_0, myMember_LESS_0, myMember_LESS_EQUA_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "EQUAL":
        return myMember_EQUAL_0;
      case "NOT_EQUAL":
        return myMember_NOT_EQUAL_0;
      case "GREATER":
        return myMember_GREATER_0;
      case "GREATER_EQUAL":
        return myMember_GREATER_EQUAL_0;
      case "LESS":
        return myMember_LESS_0;
      case "LESS_EQUA":
        return myMember_LESS_EQUA_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
