package DAS_ML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DirectionEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DirectionEnum() {
    super(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x649e0bc4ee41c435L, "DirectionEnum", "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860277");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NORTH_0 = new EnumerationDescriptor.MemberDescriptor("NORTH", "NORTH", 0x649e0bc4ee41c436L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860278");
  private final EnumerationDescriptor.MemberDescriptor myMember_SOUTH_0 = new EnumerationDescriptor.MemberDescriptor("SOUTH", "SOUTH", 0x649e0bc4ee41c438L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860280");
  private final EnumerationDescriptor.MemberDescriptor myMember_EAST_0 = new EnumerationDescriptor.MemberDescriptor("EAST", "EAST", 0x649e0bc4ee41c43aL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860282");
  private final EnumerationDescriptor.MemberDescriptor myMember_WEST_0 = new EnumerationDescriptor.MemberDescriptor("WEST", "WEST", 0x649e0bc4ee41c43cL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860284");
  private final EnumerationDescriptor.MemberDescriptor myMember_NORTH_EAST_0 = new EnumerationDescriptor.MemberDescriptor("NORTH_EAST", "NORTH_EAST", 0x649e0bc4ee41c43fL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860287");
  private final EnumerationDescriptor.MemberDescriptor myMember_SOUTH_EAST_0 = new EnumerationDescriptor.MemberDescriptor("SOUTH_EAST", "SOUTH_EAST", 0x649e0bc4ee41c441L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860289");
  private final EnumerationDescriptor.MemberDescriptor myMember_NORTH_WEST_0 = new EnumerationDescriptor.MemberDescriptor("NORTH_WEST", "NORTH_WEST", 0x649e0bc4ee41c443L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860291");
  private final EnumerationDescriptor.MemberDescriptor myMember_SOUTH_WEST_0 = new EnumerationDescriptor.MemberDescriptor("SOUTH_WEST", "SOUTH_WEST", 0x649e0bc4ee41c444L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390551860292");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x649e0bc4ee41c435L, 0x649e0bc4ee41c436L, 0x649e0bc4ee41c438L, 0x649e0bc4ee41c43aL, 0x649e0bc4ee41c43cL, 0x649e0bc4ee41c43fL, 0x649e0bc4ee41c441L, 0x649e0bc4ee41c443L, 0x649e0bc4ee41c444L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NORTH_0, myMember_SOUTH_0, myMember_EAST_0, myMember_WEST_0, myMember_NORTH_EAST_0, myMember_SOUTH_EAST_0, myMember_NORTH_WEST_0, myMember_SOUTH_WEST_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NORTH":
        return myMember_NORTH_0;
      case "SOUTH":
        return myMember_SOUTH_0;
      case "EAST":
        return myMember_EAST_0;
      case "WEST":
        return myMember_WEST_0;
      case "NORTH_EAST":
        return myMember_NORTH_EAST_0;
      case "SOUTH_EAST":
        return myMember_SOUTH_EAST_0;
      case "NORTH_WEST":
        return myMember_NORTH_WEST_0;
      case "SOUTH_WEST":
        return myMember_SOUTH_WEST_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
