package DAS_ML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RelativePositionEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RelativePositionEnum() {
    super(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x649e0bc4ee44944cL, "RelativePositionEnum", "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390552044620");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_OBSTACLE_0 = new EnumerationDescriptor.MemberDescriptor("OBSTACLE", "OBSTACLE", 0x649e0bc4ee44944dL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390552044621");
  private final EnumerationDescriptor.MemberDescriptor myMember_DESTINATION_0 = new EnumerationDescriptor.MemberDescriptor("DESTINATION", "DESTINATION", 0x649e0bc4ee44944fL, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390552044623");
  private final EnumerationDescriptor.MemberDescriptor myMember_ORIGIN_0 = new EnumerationDescriptor.MemberDescriptor("ORIGIN", "ORIGIN", 0x649e0bc4ee449451L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390552044625");
  private final EnumerationDescriptor.MemberDescriptor myMember_WATER_0 = new EnumerationDescriptor.MemberDescriptor("WATER", "WATER", 0x649e0bc4ee449454L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390552044628");
  private final EnumerationDescriptor.MemberDescriptor myMember_LAND_0 = new EnumerationDescriptor.MemberDescriptor("LAND", "LAND", 0x649e0bc4ee449458L, "r:356976db-ed45-449a-b8b5-b0d06c4a39c5(DAS_ML.structure)/7250245390552044632");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x649e0bc4ee44944cL, 0x649e0bc4ee44944dL, 0x649e0bc4ee44944fL, 0x649e0bc4ee449451L, 0x649e0bc4ee449454L, 0x649e0bc4ee449458L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_OBSTACLE_0, myMember_DESTINATION_0, myMember_ORIGIN_0, myMember_WATER_0, myMember_LAND_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "OBSTACLE":
        return myMember_OBSTACLE_0;
      case "DESTINATION":
        return myMember_DESTINATION_0;
      case "ORIGIN":
        return myMember_ORIGIN_0;
      case "WATER":
        return myMember_WATER_0;
      case "LAND":
        return myMember_LAND_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
