package DAS_ML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SEnumerationLiteral;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;

public class BatteryStatusRelationalExpression_Constraints extends BaseConstraintsDescriptor {
  public BatteryStatusRelationalExpression_Constraints() {
    super(CONCEPTS.BatteryStatusRelationalExpression$8n);
  }

  public static class Relational_operator_Property extends BasePropertyConstraintsDescriptor {
    public Relational_operator_Property(ConstraintsDescriptor container) {
      super(PROPS.relational_operator$y99t, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castEnummember(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:f7cd2215-0bd5-4435-a8f7-5ce614951a13(DAS_ML.constraints)", "8967742332347319343"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, SEnumerationLiteral propertyValue) {
      return propertyValue == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5fd8L, "DAS_ML.structure.RelationalOperatorEnum"), 0x7c73d2235ccb5fddL, "EQUAL") || propertyValue == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5fd8L, "DAS_ML.structure.RelationalOperatorEnum"), 0x7c73d2235ccb5fe0L, "NOT_EQUAL");
    }
  }
  public static class Status_Property extends BasePropertyConstraintsDescriptor {
    public Status_Property(ConstraintsDescriptor container) {
      super(PROPS.status$Jtsz, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castEnummember(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:f7cd2215-0bd5-4435-a8f7-5ce614951a13(DAS_ML.constraints)", "4581770562466284539"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, SEnumerationLiteral propertyValue) {
      return propertyValue == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5ff4L, "DAS_ML.structure.StatusEnum"), 0x7c73d2235ccb5ff9L, "ERROR") || propertyValue == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5ff4L, "DAS_ML.structure.StatusEnum"), 0x7c73d2235ccb5ff5L, "NORMAL");

    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.relational_operator$y99t, new Relational_operator_Property(this));
    properties.put(PROPS.status$Jtsz, new Status_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BatteryStatusRelationalExpression$8n = MetaAdapterFactory.getConcept(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5fc4L, "DAS_ML.structure.BatteryStatusRelationalExpression");
  }

  private static final class PROPS {
    /*package*/ static final SProperty relational_operator$y99t = MetaAdapterFactory.getProperty(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235cc8afffL, 0x7c73d2235ccb5fedL, "relational_operator");
    /*package*/ static final SProperty status$Jtsz = MetaAdapterFactory.getProperty(0xb5193d0ff2e3489fL, 0x8a11cbd304ed9c53L, 0x7c73d2235ccb5fc4L, 0x7c73d2235ccb6001L, "status");
  }
}
